"""Add muscle_group and photo_url to ExerciseType

Revision ID: 603444c8e2aa
Revises: 
Create Date: 2025-07-17 22:02:46.913711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603444c8e2aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_type', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('muscle_group')

    # ### end Alembic commands ###
